In [6]:
import torch 

In [9]:
# create a tensor
some_tensor = torch.rand(3,5)
some_tensor

tensor([[0.3853, 0.3795, 0.5974, 0.5601, 0.0018],
        [0.7808, 0.7791, 0.9069, 0.8809, 0.8604],
        [0.9635, 0.2816, 0.3078, 0.5389, 0.9701]])

In [10]:
print(some_tensor.dtype)
print(some_tensor.shape)
print(some_tensor.device)


torch.float32
torch.Size([3, 5])
cpu


### Manipulating Tensors (tensor operations)

Tensor operations includes:
* Addition
* Subtraction
* Multiplaction (element*wise)
* Division
* Mat. Multification
* 

In [12]:
# Create a tensor
tensr = torch.tensor([1,2,3])
tensr + 10

tensor([11, 12, 13])

In [13]:
# subtraction
tensr - 20


tensor([-19, -18, -17])

In [15]:
tensr /10

tensor([0.1000, 0.2000, 0.3000])

In [16]:
# Try out pytorch inbuilt fns
torch.mul(tensr, 10)

tensor([10, 20, 30])

As you can see when we use all the operations it performs element wise
It is recommended to use operators rather than using the function unless there are some exceptions

### Matrix multiplicatiom

Two main ways for performing multiplication in neural networks and deep learning:

1. Element-wise (as seen above)
2. Matrix Multiplication (dot product)

There are twomain rules for performing mutiplication needs to satisfy
1. inner dimensions must match:
   * `(3,2)  @ (3,2) won't work`
   * ` (3,2) @ (2,3) will work`
   * ` (5,2) @ (2,8) will work`

2. Resulting matrix have the shape of the outer dimensions
   * `3,2 @ 2,3 will be 3,3`
   * `5,2 @ 2,8 will be 5,8`

In [20]:
MATRIX1 = torch.tensor([1,2,3])

In [21]:
MATRIX1 * MATRIX1

tensor([1, 4, 9])

In [22]:
torch.matmul(MATRIX1, MATRIX1)

tensor(14)

In [26]:

torch.matmul(torch.rand(5,2),torch.rand(2,8)).shape

torch.Size([5, 8])

In [28]:
# torch.mm is alias of torch.matmul
torch.mm(torch.rand(2,3), torch.rand(3,4))


tensor([[0.7332, 1.1481, 0.2354, 1.3113],
        [1.5553, 1.7199, 0.7786, 2.2074]])

## Aggregation Utils

min, max, sum, 

In [31]:
tensor = torch.arange(1,10)
tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
tensor.min()

tensor(1)

In [33]:
tensor.max()

tensor(9)

In [34]:
# index of min value
tensor.argmin()

tensor(0)

In [35]:
# inde xof max value
tensor.argmax()

tensor(8)

In [36]:
# sum
tensor.sum()

tensor(45)

In [38]:
# mean requires flating point or a long
tensor.type(torch.float16).mean()

tensor(5., dtype=torch.float16)

### ReShape

You can reshape any tensor, only make sure that the shape dimensions multiplications are same from where it is being reshaped

In [40]:
x = torch.arange(1,10)

In [41]:
x_reshaped = x.reshape(1, 9)
x_reshaped

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [42]:
x.reshape(3,3) 

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### View

Creates a view of the tensor, it is very similar to reshape, but it still contains the reference of the original tensor, so if you change anything in the tensor will its view will also change and viceversa


In [44]:
x_view = x.view(3,3)
x_view

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [45]:
x[3] = 99

In [46]:
x_view

tensor([[ 1,  2,  3],
        [99,  5,  6],
        [ 7,  8,  9]])

In [47]:
x_view[:, 2] = 80

In [48]:
x

tensor([ 1,  2, 80, 99,  5, 80,  7,  8, 80])

In [52]:
x_stacked = torch.stack((x,x,x)
                       )

In [53]:
x_stacked

tensor([[ 1,  2, 80, 99,  5, 80,  7,  8, 80],
        [ 1,  2, 80, 99,  5, 80,  7,  8, 80],
        [ 1,  2, 80, 99,  5, 80,  7,  8, 80]])

In [60]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous  shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"New tensor: {x_squeezed}")
print(f"New tensor shape ")

Previous tensor: tensor([[ 1,  2, 80, 99,  5, 80,  7,  8, 80]])
Previous  shape: torch.Size([1, 9])
New tensor: tensor([ 1,  2, 80, 99,  5, 80,  7,  8, 80])


squeeze removes a single dimensions and unsqueeze adds different diemsions, permute rearranges

In [64]:
x_original = torch.rand(size=(10,10,3)) # example of an rgb image of 10,10 pxies and 3 colour channels [height, width, colour_channels]

#rearrange use permute 
#permute just returns a different view, so it is a reference 
x_permuted = x_original.permute(2, 0, 1) # this will rearrange to [colour_channels, height, width]
print(f"X_original shape: {x_original.shape}")

print(f"Permuted shape: {x_permuted.shape}")


X_original shape: torch.Size([10, 10, 3])
Permuted shape: torch.Size([3, 10, 10])


## Indexing (selecting data from tensors)

Indexing with pytorch is very similar to NumPy


In [65]:
x = torch.arange(1, 10 ).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [68]:
x[0][0]

tensor([1, 2, 3])

In [67]:
x[0,0]

tensor([1, 2, 3])

both x[0][0] and x[0,0] can be used to same 

In [69]:
import numpy as np
import math

# Create random input and output data
x = np.linspace(-math.pi, math.pi, 2000)
y = np.sin(x)

# Randomly initialize weights
a = np.random.randn()
b = np.random.randn()
c = np.random.randn()
d = np.random.randn()

learning_rate = 1e-6
for t in range(2000):
    # Forward pass: compute predicted y
    # y = a + b x + c x^2 + d x^3
    y_pred = a + b * x + c * x ** 2 + d * x ** 3

    # Compute and print loss
    loss = np.square(y_pred - y).sum()
    if t % 100 == 99:
        print(t, loss)

    # Backprop to compute gradients of a, b, c, d with respect to loss
    grad_y_pred = 2.0 * (y_pred - y)
    grad_a = grad_y_pred.sum()
    grad_b = (grad_y_pred * x).sum()
    grad_c = (grad_y_pred * x ** 2).sum()
    grad_d = (grad_y_pred * x ** 3).sum()

    # Update weights
    a -= learning_rate * grad_a
    b -= learning_rate * grad_b
    c -= learning_rate * grad_c
    d -= learning_rate * grad_d

print(f'Result: y = {a} + {b} x + {c} x^2 + {d} x^3')

99 1479.507628425637
199 1049.5582634849402
299 745.3025618151387
399 529.9945658473349
499 377.63083704003725
599 269.8099184826438
699 193.50993167353377
799 139.5158823355651
899 101.30673591065647
999 74.26785124778438
1099 55.13365556011581
1199 41.59325070913542
1299 32.01131861608006
1399 25.23061864862825
1499 20.432223956702334
1599 17.03661705016868
1699 14.633699613431334
1799 12.933263617354047
1899 11.729941965635438
1999 10.878405652685583
Result: y = -0.048056357312097446 + 0.8567557739339094 x + 0.00829052129757416 x^2 + -0.09333251282543256 x^3


In [70]:
# -*- coding: utf-8 -*-

import torch
import math


dtype = torch.float
# device = torch.device("cpu")
device = torch.device("cuda:0") # Uncomment this to run on GPU

# Create random input and output data
x = torch.linspace(-math.pi, math.pi, 2000, device=device, dtype=dtype)
y = torch.sin(x)

# Randomly initialize weights
a = torch.randn((), device=device, dtype=dtype)
b = torch.randn((), device=device, dtype=dtype)
c = torch.randn((), device=device, dtype=dtype)
d = torch.randn((), device=device, dtype=dtype)

learning_rate = 1e-6
for t in range(2000):
    # Forward pass: compute predicted y
    y_pred = a + b * x + c * x ** 2 + d * x ** 3

    # Compute and print loss
    loss = (y_pred - y).pow(2).sum().item()
    if t % 100 == 99:
        print(t, loss)

    # Backprop to compute gradients of a, b, c, d with respect to loss
    grad_y_pred = 2.0 * (y_pred - y)
    grad_a = grad_y_pred.sum()
    grad_b = (grad_y_pred * x).sum()
    grad_c = (grad_y_pred * x ** 2).sum()
    grad_d = (grad_y_pred * x ** 3).sum()

    # Update weights using gradient descent
    a -= learning_rate * grad_a
    b -= learning_rate * grad_b
    c -= learning_rate * grad_c
    d -= learning_rate * grad_d


print(f'Result: y = {a.item()} + {b.item()} x + {c.item()} x^2 + {d.item()} x^3')

99 251.90322875976562
199 178.31402587890625
299 127.09652709960938
399 91.41641235351562
499 66.54051971435547
599 49.18370819091797
699 37.064239501953125
799 28.59569549560547
899 22.674280166625977
999 18.531143188476562
1099 15.630403518676758
1199 13.598322868347168
1299 12.173957824707031
1399 11.175004959106445
1499 10.474068641662598
1599 9.981979370117188
1699 9.636360168457031
1799 9.393506050109863
1899 9.22278881072998
1999 9.10273551940918
Result: y = -0.01721774972975254 + 0.8522889018058777 x + 0.002970347413793206 x^2 + -0.0926971361041069 x^3


# Pytorch tensors & NumPy

Numpy is a popular scientific Python numerical computing library.
And because of this, PyTorch has functionalty to interact with it.
* Data in NumPy, want in PyTorch tensor -> torch.from_numpy(ndarray)
* PyTorch tensor -> NumPY => torch.Tensor.numpy()
    

In [71]:
import torch
import numpy as np

array = np.arange(1., 8.)
tensor = torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

Default numpy is float64 or int64, so when converting from numpy to torch, it reflects the nump


In [72]:
array[0] = 11
array,tensor

(array([11.,  2.,  3.,  4.,  5.,  6.,  7.]),
 tensor([11.,  2.,  3.,  4.,  5.,  6.,  7.], dtype=torch.float64))

they both share memory


In [73]:
tensor.numpy()


array([11.,  2.,  3.,  4.,  5.,  6.,  7.])

## Reproducible random numbers

`start with random numbers - tensor operations -> update random numbers to trying to make them better represenataion of the data -> again -> again-> again ...`

In [76]:
torch.rand(3,3), torch.rand(3,3)

(tensor([[0.1175, 0.0328, 0.1520],
         [0.5459, 0.5087, 0.1619],
         [0.3016, 0.3013, 0.7370]]),
 tensor([[0.7368, 0.9913, 0.7414],
         [0.9076, 0.5801, 0.9133],
         [0.0069, 0.6980, 0.7764]]))

to reduce the randomness in neural networks and PyTorch comes the concept of **random seed**.


In [85]:
RANDOM_SEED = 48 # this is the seed used to  get the random
torch.random.manual_seed(RANDOM_SEED)
print(torch.rand(3,3))
torch.random.manual_seed(RANDOM_SEED)
print(torch.rand(3,3))
torch.random.manual_seed(RANDOM_SEED)
print(torch.rand(3,3))
torch.random.manual_seed(RANDOM_SEED)
torch.rand(3,3)

tensor([[0.4775, 0.1798, 0.2428],
        [0.2166, 0.9245, 0.6069],
        [0.5380, 0.7022, 0.7608]])
tensor([[0.4775, 0.1798, 0.2428],
        [0.2166, 0.9245, 0.6069],
        [0.5380, 0.7022, 0.7608]])
tensor([[0.4775, 0.1798, 0.2428],
        [0.2166, 0.9245, 0.6069],
        [0.5380, 0.7022, 0.7608]])


tensor([[0.4775, 0.1798, 0.2428],
        [0.2166, 0.9245, 0.6069],
        [0.5380, 0.7022, 0.7608]])

always make sure manual_seed is set everytime

## GPU

In [86]:
# check gpu access
torch.cuda.is_available()

True

In [90]:
# Setup device agnostic code
# set device variable

device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
device

device(type='cuda')

In [89]:
torch.cuda.device_count()

1

### Putting tensors and models on GPU

Computations on CPU is faster


In [91]:
# cpu
tensor = torch.tensor([1,3,2,4])
tensor, tensor.device

(tensor([1, 3, 2, 4]), device(type='cpu'))

In [93]:
# move it to gpu
tensor_gpu = tensor.to(device)

In [95]:
# moving tensor back to cpu
# the below will throw the error hence we have to first move to cpu then convert to numpy
# tensor_gpu.numpy()

tensor_gpu.cpu().numpy()

array([1, 3, 2, 4])